=== AKielhorn/Prozessbeschreibung/prozess.dtd
<!-- 
% Copyright 2019 Axel Kielhorn
% Lizenz: CC-BY-SA 4.0 Unported http://creativecommons.org/licenses/by-sa/4.0/deed.de
-->
<!-- prozess
     pnr	Prozessnummer
     pname	Prozessname
     pverantwortlich Prozessverantwortlicher
     pschritt	Prozesschritt, mindestens 1
     pversion   Versionsnummer (optional)
-->	
<!ELEMENT prozess (pnr, pname, pverantwortlich, pversion?, pschritt+)>
<!ELEMENT pnr (#PCDATA)>
<!ELEMENT pname (#PCDATA)>
<!ELEMENT pverantwortlich (#PCDATA)>
<!ELEMENT pversion (#PCDATA)>
<!-- pschritt
     psnr	Prozessschrittnummer
     pskurz	Prozess Kurzbeschreibung (für Visualisierung)
     pslang	Prozess Langbeschreibung für tabelarische Form (optional)
     psindoc    Benötigte Dokumente
     psoutdoc	Erzeugte Dokumente
     aschritt	Arbeitsschritt, mindestens 1
-->
<!ELEMENT pschritt (psnr, pskurz, pslang?, psindoc*, psoutdoc*, (aschritt, eschritt)+)>
<!ELEMENT psnr (#PCDATA)>
<!ELEMENT pskurz (#PCDATA)>
<!ELEMENT pslang (#PCDATA)>
<!-- aschritt	Arbeitsschritt (grün)
     asverantwortlich	Verantwortlicher 
     askurz	Arbeitsschritt Kurzbeschreibung (für Visualisierung)
     aslang	Arbeitsschritt Langbeschreibung für tabelarische Form (optional)
     -->
<!ELEMENT aschritt (askurz, aslang*, asverantwortlich)>
<!ELEMENT askurz (#PCDATA)>
<!ELEMENT aslang (#PCDATA)>
<!ELEMENT asverantwortlich (#PCDATA)>
<!-- eschritt	Ergebnisschritt (rot)
     eskurz	Arbeitsschritt Kurzbeschreibung (für Visualisierung)
     eslang	Arbeitsschritt Langbeschreibung für tabelarische Form (optional)
     -->
<!ELEMENT eschritt (eskurz, eslang*)>
<!ELEMENT eskurz (#PCDATA)>
<!ELEMENT eslang (#PCDATA)>
<!-- psindoc, psoutdoc
     -->
<!ELEMENT psindoc (docnr, docname, docverantwortlich)>
<!ELEMENT psoutdoc (docnr, docname, docverantwortlich, docan+)>
<!ELEMENT docnr (#PCDATA)>
<!ELEMENT docname (#PCDATA)>
<!ELEMENT docverantwortlich (#PCDATA)>
<!ELEMENT docan(#PCDATA)>

=== AKielhorn/Prozessbeschreibung/XML-Lua/prozess.xml
<?xml version="1.0"?>
<!DOCTYPE prozess SYSTEM "prozess.dtd">
<!-- 
% Copyright 2019 Axel Kielhorn
% Lizenz: CC-BY-SA 4.0 Unported http://creativecommons.org/licenses/by-sa/4.0/deed.de
-->
<prozess>
        <pnr>
                1.0
        </pnr>
        <pname>
                Prozessbeschreibung
        </pname>
        <pverantwortlich>
                Rechtsabteilung
        </pverantwortlich>
        <pversion>
                1.0
        </pversion>
        <pschritt>
                <psnr>
                        010
                </psnr>
                <pskurz>
                        Prozess beschreiben
                </pskurz>
                <psindoc>
                        <docnr>
                                PD 3710
                        </docnr>
                        <docname>
                                DTD.html
                        </docname>
                        <docverantwortlich>
                                LA
                        </docverantwortlich>
                </psindoc>
                <psindoc>
                        <docnr>
                                PD 3711
                        </docnr>
                        <docname>
                                Prozessbeschreibung.html
                        </docname>
                        <docverantwortlich>
                                LA
                        </docverantwortlich>
                </psindoc>
                <psoutdoc>
                        <docnr>
                                PD 4711
                        </docnr>
                        <docname>
                                Prozess.xml
                        </docname>
                        <docverantwortlich>
                                Rechtsabteilung
                        </docverantwortlich>
                        <docan>
                                PL
                        </docan>
                </psoutdoc>
                <aschritt>
                        <askurz>
                                DTD erstellen
                        </askurz>
                        <asverantwortlich>
                                EDV
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
                                DTD validiert
                        </eskurz>
                </eschritt>
                <aschritt>
                        <askurz>
                                XML erstellen
                        </askurz>
                        <aslang>
                                XML erstellen, mit xmllint gegen die DTD validieren.
                        </aslang>
                        <asverantwortlich>
                                MA Rechtsabteilung
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
                                XML validiert
                        </eskurz>
                </eschritt>
        </pschritt>
        <pschritt>
                <psnr>
                        020
                </psnr>
                <pskurz>
                        Prozess visualisieren
                </pskurz>
                <psoutdoc>
                        <docnr>
                                PD 4712
                        </docnr>
                        <docname>
                                Prozess.pdf
                        </docname>
                        <docverantwortlich>
                                Rechtsabteilung
                        </docverantwortlich>
                        <docan>
                                Web-Server
                        </docan>
                </psoutdoc>
                <psoutdoc>
                        <docnr>
                                PD 4713
                        </docnr>
                        <docname>
                                Prozess-g.pdf
                        </docname>
                        <docverantwortlich>
                                Rechtsabteilung
                        </docverantwortlich>
                        <docan>
                                Web-Server
                        </docan>
                </psoutdoc>
                <aschritt>
                        <askurz>
                                Tabellarische Version erstellen und veröffentlichen
                        </askurz>
                        <aslang>
                                Tabellarische Version mit ConTeXt erstellen und auf dem Web-Server veröffentlichen.
                        </aslang>
                        <asverantwortlich>
                                EDV
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
                                Tabellarische Version auf dem Web-Server.
                        </eskurz>
                </eschritt>
                <aschritt>
                        <askurz>
                                Graphische Version erstellen und veröffentlichen.
                        </askurz>
                        <aslang>
                                Das Werkzeug existiert noch nicht.
                        </aslang>
                        <asverantwortlich>
                                EDV
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
                                Graphische Version auf Webserver
                        </eskurz>
                </eschritt>
        </pschritt>
        <pschritt>
                <psnr>
                        030
                </psnr>
                <pskurz>
                        Dokumentenfluss erstellen
                </pskurz>
                <psoutdoc>
                        <docnr>
                                PD 4722
                        </docnr>
                        <docname>
                                Dokumentenfluss.pdf
                        </docname>
                        <docverantwortlich>
                                EDV
                        </docverantwortlich>
                        <docan>
                                Web-Server
                        </docan>
                </psoutdoc>
                <aschritt>
                        <askurz>
                                Alle XML-Dateien mit system-in.py bearbeiten.
                        </askurz>
                        <aslang>
                                Das Werkzeug existiert noch nicht.
                        </aslang>
                        <asverantwortlich>
                                EDV
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
                                Jedes Dokument hat genau einen Verantwortlichen und mindestens einen Empfänger.
                        </eskurz>
                </eschritt>
        </pschritt>
</prozess>

=== AKielhorn/Prozessbeschreibung/prozess.xml
<?xml version="1.0"?>
<!DOCTYPE prozess SYSTEM "prozess.dtd">
<!-- 
% Copyright 2019 Axel Kielhorn
% Lizenz: CC-BY-SA 4.0 Unported http://creativecommons.org/licenses/by-sa/4.0/deed.de
-->
<prozess>
        <pnr>
                1.0
        </pnr>
        <pname>
                Prozessbeschreibung
        </pname>
        <pverantwortlich>
                Rechtsabteilung
        </pverantwortlich>
        <pversion>
                1.0
        </pversion>
        <pschritt>
                <psnr>
                        010
                </psnr>
                <pskurz>
                        Prozess beschreiben
                </pskurz>
                <psindoc>
                        <docnr>
                                PD 3710
                        </docnr>
                </psindoc>
                <psindoc>
                        <docnr>
                                PD 3711
                        </docnr>
                </psindoc>
                <psoutdoc>
                        <docnr>
                                PD 4711
                        </docnr>
                </psoutdoc>
                <aschritt>
                        <askurz>
                                DTD erstellen
                        </askurz>
                        <asverantwortlich>
                                EDV
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
                                DTD validiert
                        </eskurz>
                </eschritt>
                <aschritt>
                        <askurz>
                                XML erstellen
                        </askurz>
                        <aslang>
                                XML erstellen, mit xmllint gegen die DTD validieren.
                        </aslang>
                        <asverantwortlich>
                                MA Rechtsabteilung
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
                                XML validiert
                        </eskurz>
                </eschritt>
        </pschritt>
        <pschritt>
                <psnr>
                        020
                </psnr>
                <pskurz>
                        Prozess visualisieren
                </pskurz>
                <psoutdoc>
                        <docnr>
                                PD 4712
                        </docnr>
                </psoutdoc>
                <psoutdoc>
                        <docnr>
                                PD 4713
                        </docnr>
                </psoutdoc>
                <aschritt>
                        <askurz>
                                Tabellarische Version erstellen und veröffentlichen
                        </askurz>
                        <aslang>
                                Tabellarische Version mit ConTeXt erstellen und auf dem Web-Server veröffentlichen.
                        </aslang>
                        <asverantwortlich>
                                EDV
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
                                Tabellarische Version auf dem Web-Server.
                        </eskurz>
                </eschritt>
                <aschritt>
                        <askurz>
                                Graphische Version erstellen und veröffentlichen.
                        </askurz>
                        <aslang>
                                Das Werkzeug existiert noch nicht.
                        </aslang>
                        <asverantwortlich>
                                EDV
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
                                Graphische Version auf Webserver
                        </eskurz>
                </eschritt>
        </pschritt>
        <pschritt>
                <psnr>
                        030
                </psnr>
                <pskurz>
                        Dokumentenfluss erstellen
                </pskurz>
                <psoutdoc>
                        <docnr>
                                PD 4722
                        </docnr>
                </psoutdoc>
                <aschritt>
                        <askurz>
                                Alle XML-Dateien mit panalyse.lua bearbeiten.
                        </askurz>
                        <aslang>
				Alle XML-Dateien mit panalyse.lua bearbeiten.
				Ergebnis mit doclist-style bearbeiten.
                        </aslang>
                        <asverantwortlich>
                                EDV
                        </asverantwortlich>
                </aschritt>
                <eschritt>
                        <eskurz>
				Doclist.pdf auf Webserver installiert.
                        </eskurz>
                </eschritt>
        </pschritt>
</prozess>
